controllers:
    resource: ../src/Controller/
    type: attribute

app_admin_controller:
    resource: ../src/Controller/Admin
    prefix: /admin
    type: attribute
index:
    path: /
    controller: App\Controller\DefaultController::index